apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "external-auth-server.fullname" . }}
  labels:
    {{- include "external-auth-server.labels" . | nindent 4 }}
data:
  node-extra-ca-certs: {{ default "" .Values.nodeExtraCaCerts | quote }}
  revoked-jtis: {{ .Values.revokedJtis | toJson | quote }}
