apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "external-auth-server.fullname" . }}
  labels:
    {{- include "external-auth-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "external-auth-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
        {{- tpl (toYaml .Values.podAnnotations) $ | nindent 8 }}
        {{- end }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "external-auth-server.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- tpl (toYaml .Values.podLabels) $ | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
          {{- end }}
          env:
            - name: NODE_ENV
              value: "production"
            - name: EAS_PORT
              value: "8080"
            - name: EAS_GRPC_PORT
              value: "50051"
            {{- if .Values.logLevel }}
            - name: EAS_LOG_LEVEL
              value: "{{ .Values.logLevel }}"
            {{- end }}
            {{- if .Values.revokedJtis }}
            - name: EAS_REVOKED_JTIS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: rovoked-jtis
            {{- end }}
            {{- if .Values.storeOpts }}
            - name: EAS_STORE_OPTS
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: store-opts
            {{- end }}
            {{- if .Values.configTokenStores }}
            - name: EAS_CONFIG_TOKEN_STORES
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: config-token-stores
            {{- end }}
            {{- if .Values.configTokens }}
            - name: EAS_CONFIG_TOKENS
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: config-tokens
            {{- end }}
            - name: EAS_CONFIG_TOKEN_SIGN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: config-token-sign-secret
            - name: EAS_CONFIG_TOKEN_ENCRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: config-token-encrypt-secret
            - name: EAS_ENCRYPT_IV_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: config-token-encrypt-iv-secret
            - name: EAS_ISSUER_SIGN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: issuer-sign-secret
            - name: EAS_ISSUER_ENCRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: issuer-encrypt-secret
            - name: EAS_COOKIE_SIGN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: cookie-sign-secret
            - name: EAS_COOKIE_ENCRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: cookie-encrypt-secret
            - name: EAS_SESSION_ENCRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: session-encrypt-secret
            {{- if .Values.nodeExtraCaCerts }}
            - name: NODE_EXTRA_CA_CERTS
              value: "/tmp/certs/node-extra-ca-certs.crt"
            {{- end }}
            {{- if .Values.backchannelLogoutConfig }}
            - name: EAS_BACKCHANNEL_LOGOUT_CONFIG
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: backchannel-logout-config
            {{- end }}
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v.value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 50051
              protocol: TCP
          volumeMounts:
            - name: node-extra-ca-certs
              mountPath: /tmp/certs
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 12 }}
{{- end }}

          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: node-extra-ca-certs
        configMap:
          name: {{ include "external-auth-server.fullname" . }}
          items:
            - key: node-extra-ca-certs
              path: node-extra-ca-certs.crt
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- end }}
